services:
  usuarios:
    image: microservicio-usuarios
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    networks:
      - my-network
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_user
    ports:
      - "3306:3306"
    networks:
      - my-network
networks:
  my-network: